mutation InsertCredential($object: credentials_insert_input!) {
  insert_credentials_one(object: $object) {
    id
  }
}

mutation UpdateCredential(
  $pk_columns: credentials_pk_columns_input!
  $_set: credentials_set_input!
) {
  update_credentials_by_pk(pk_columns: $pk_columns, _set: $_set) {
    id
  }
}

mutation DeleteCredential($id: uuid!) {
  delete_credentials_by_pk(id: $id) {
    id
  }
}

mutation UpdateCredentials($id: uuid!, $object: credentials_set_input, $members: [member_credentials_insert_input!]!) {
  update_credentials_by_pk(
    pk_columns: { id: $id }
    _set: $object
  ) {
    id
  }

  delete_member_credentials(where: {credential_id: {_eq: $id}}) {
    affected_rows
  }

  insert_member_credentials(objects: $members) {
    affected_rows
  }
}
