mutation InsertCredential($object: credentials_insert_input!) {
  insert_credentials_one(object: $object) {
    id
  }
}

mutation UpdateCredential(
  $pk_columns: credentials_pk_columns_input!
  $_set: credentials_set_input!
) {
  update_credentials_by_pk(pk_columns: $pk_columns, _set: $_set) {
    id
  }
}

mutation DeleteCredential($id: uuid!) {
  delete_credentials_by_pk(id: $id) {
    id
  }
}

query Credential($id: uuid!) {
  credentials_by_pk(id: $id) {
    id
    user_id
    datasource_id
    username
  }
}

mutation UpdateCredentials($id: uuid!, $username: String!, $password: String!) {
  update_sql_credentials_by_pk(
    pk_columns: { id: $id }
    _set: { username: $username, password: $password }
  ) {
    id
  }
}

query Credentials($offset: Int, $limit: Int) {
  credentials(offset: $offset, limit: $limit, order_by: {created_at: desc}) {
    id
    user_id
    username
    created_at
    updated_at
    datasource {
      id
      name
    }
    user {
      id
      display_name
    }
  }
  credentials_aggregate {
    aggregate {
      count
    }
  }
}
