mutation InsertCredential($object: credentials_insert_input!) {
  insert_credentials_one(object: $object) {
    id
  }
}

mutation UpdateCredential(
  $pk_columns: credentials_pk_columns_input!
  $_set: credentials_set_input!
) {
  update_credentials_by_pk(pk_columns: $pk_columns, _set: $_set) {
    id
  }
}

mutation DeleteCredential($id: uuid!) {
  delete_credentials_by_pk(id: $id) {
    id
  }
}

mutation UpdateCredentials($id: uuid!, $username: String!, $password: String!) {
  update_sql_credentials_by_pk(
    pk_columns: { id: $id }
    _set: { username: $username, password: $password }
  ) {
    id
  }
}

mutation DeleteMemberCredentials($id: uuid!) {
  delete_members_credentials(where: { id: { _eq: $id }}) {
    affected_rows
  }
}

mutation InsertMembersCredentials($objects: [members_credentials_insert_input!]!) {
  insert_members_credentials(objects: $objects) {
    affected_rows
  }
}
