fragment BranchesFields on branches {
  id
  name
  status
  versions(limit: 1, order_by: { created_at: desc }) {
    id
    dataschemas_aggregate {
      aggregate {
        count
      }
    }
  }
}

fragment TeamFields on teams {
  id
  name
  created_at
  updated_at
  members {
    member_roles {
      id
      team_role
    }
    user {
      id
      avatar_url
      display_name
      account {
        email
      }
    }
  }
}

query CurrentUser($id: uuid!) {
  users_by_pk(id: $id) {
    id
    display_name
    avatar_url
    account {
      email
    }

    datasources {
      id
      name
      db_params
      db_type
      created_at
      updated_at
      branches(where: { status: { _eq: active } }) {
        ...BranchesFields
      }
      sql_credentials {
        id
        username
        created_at
        updated_at
        user {
          id
          display_name
        }
      }
    }

    alerts(order_by: { created_at: desc }) {
      id
      name
      delivery_type
      delivery_config
      trigger_config
      created_at
      updated_at
      schedule
      user {
        id
        avatar_url
        display_name
        account {
          email
        }
      }
      exploration {
        id
        playground_state
      }
    }

    reports(order_by: { created_at: desc }) {
      id
      name
      schedule
      delivery_type
      delivery_config
      created_at
      updated_at
      user {
        id
        avatar_url
        display_name
        account {
          email
        }
      }
      exploration {
        id
        playground_state
      }
    }

    members(order_by: { created_at: desc }) {
      member_roles {
        id
        team_role
      }
      user {
        id
        avatar_url
        display_name
        account {
          email
        }
      }
      team {
        ...TeamFields
      }
    }
  }
}

subscription SubCurrentUser($id: uuid!) {
  users_by_pk(id: $id) {
    id
    display_name
    avatar_url
    account {
      email
    }

    datasources {
      id
      name
      db_params
      db_type
      created_at
      updated_at
      branches(where: { status: { _eq: active } }) {
        ...BranchesFields
      }
      sql_credentials {
        id
        username
        created_at
        updated_at
        user {
          id
          display_name
        }
      }
    }

    alerts(order_by: { created_at: desc }) {
      id
      name
      delivery_type
      delivery_config
      trigger_config
      created_at
      updated_at
      schedule
      user {
        id
        avatar_url
        display_name
        account {
          email
        }
      }
      exploration {
        id
        playground_state
      }
    }

    reports(order_by: { created_at: desc }) {
      id
      name
      schedule
      delivery_type
      delivery_config
      created_at
      updated_at
      user {
        id
        avatar_url
        display_name
        account {
          email
        }
      }
      exploration {
        id
        playground_state
      }
    }

    members(order_by: { created_at: desc }) {
      member_roles {
        id
        team_role
      }
      user {
        id
        avatar_url
        display_name
        account {
          email
        }
      }
      team {
        ...TeamFields
      }
    }
  }
}

mutation UpdateUserInfo(
  $user_id: uuid!
  $display_name: String
  $email: citext
) {
  update_users_by_pk(
    pk_columns: { id: $user_id }
    _set: { display_name: $display_name }
  ) {
    id
  }
  update_auth_accounts(
    where: { user_id: { _eq: $user_id } }
    _set: { email: $email }
  ) {
    affected_rows
  }
}
