query Credentials ($teamId: uuid!) {
  sql_credentials(where: {datasource: {team_id: {_eq: $teamId}}}) {
    id
    username
    created_at
    user {
      display_name
    }
    datasource {
      db_type
      db_params
    }
  }
}

mutation InsertSqlCredentials ($object: sql_credentials_insert_input!) { 
  insert_sql_credentials_one(object: $object) {
    id
  }
}
