import RootLayout from "@/layouts/RootLayout";
import { queryMocks } from "@/mocks/logs";

import QueryLogsTable from ".";

import type { StoryFn, Meta } from "@storybook/react";

export default {
  title: "Components/Logs/QueryLogsTable",
  component: QueryLogsTable,
} as Meta<typeof QueryLogsTable>;

const Template: StoryFn<typeof QueryLogsTable> = (args) => (
  <RootLayout>
    <QueryLogsTable {...args} />
  </RootLayout>
);

export const Default = Template.bind({});

Default.args = {
  logs: [
    {
      id: "552c5e1d-6420-411a-acff-cd9a422d70c6",
      created_at: "2023-10-17T04:06:09.486495+00:00",
      updated_at: "2023-10-17T04:06:09.486495+00:00",
      request_id: "11089db8-ffdd-4d24-b154-9a71fffda84b-span-1",
      start_time: "2023-10-17T04:05:09.419+00:00",
      end_time: "2023-10-17T04:05:09.422+00:00",
      duration: 3,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "gh-api.clickhouse.tech (Yandex Demo)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 3 },
        nodes: [],
      },
    },
    {
      id: "20d14583-d13a-4126-8bb6-7fde5268ac21",
      created_at: "2023-10-17T04:06:09.486495+00:00",
      updated_at: "2023-10-17T04:06:09.486495+00:00",
      request_id: "54dd1c3d-bd7c-4b06-9171-e48a508556c8-span-1",
      start_time: "2023-10-17T04:05:09.389+00:00",
      end_time: "2023-10-17T04:05:09.393+00:00",
      duration: 4,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "gh-api.clickhouse.tech (Yandex Demo)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 3 },
        nodes: [],
      },
    },
    {
      id: "8a940cf1-fe11-4e5f-b4ae-3021cd625972",
      created_at: "2023-10-17T04:06:09.486495+00:00",
      updated_at: "2023-10-17T04:06:09.486495+00:00",
      request_id: "bf09da0e-3f66-4b86-9333-44145a780bc1-span-1",
      start_time: "2023-10-17T04:05:09.448+00:00",
      end_time: "2023-10-17T04:05:09.449+00:00",
      duration: 1,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "gh-api.clickhouse.tech (Yandex Demo)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 2 },
        nodes: [],
      },
    },
    {
      id: "c7ef151f-de86-4586-8d8b-a3d5f58c355b",
      created_at: "2023-10-16T13:05:06.745287+00:00",
      updated_at: "2023-10-16T13:05:06.745287+00:00",
      request_id: "183bbc4a-6abb-4e77-af63-3d56b6c0beab-span-1",
      start_time: "2023-10-16T13:04:58.893+00:00",
      end_time: "2023-10-16T13:04:58.893+00:00",
      duration: 0,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "Ecom (demo db)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 2 },
        nodes: [],
      },
    },
    {
      id: "d76e4636-797b-4cc4-826d-24a926d10f7b",
      created_at: "2023-10-16T10:46:04.960497+00:00",
      updated_at: "2023-10-16T10:46:04.960497+00:00",
      request_id: "b0427927-41f0-4a59-8d5a-2722177b11b0-span-1",
      start_time: "2023-10-16T10:45:12.357+00:00",
      end_time: "2023-10-16T10:45:12.358+00:00",
      duration: 1,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "Ecom (demo db)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 2 },
        nodes: [],
      },
    },
    {
      id: "5e1574b0-0c56-4e84-b184-1bbc74de164c",
      created_at: "2023-10-16T04:05:02.651383+00:00",
      updated_at: "2023-10-16T04:05:02.651383+00:00",
      request_id: "1bf9a94d-bd32-4194-b2d0-61e6c40a387c-span-1",
      start_time: "2023-10-16T04:05:02.605+00:00",
      end_time: "2023-10-16T04:05:02.608+00:00",
      duration: 3,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "gh-api.clickhouse.tech (Yandex Demo)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 3 },
        nodes: [],
      },
    },
    {
      id: "c99f8b45-20bf-4835-bc6c-a4faa3fc2b85",
      created_at: "2023-10-16T04:05:02.651383+00:00",
      updated_at: "2023-10-16T04:05:02.651383+00:00",
      request_id: "c87bb802-93fa-404a-a673-e66192b6eb9a-span-1",
      start_time: "2023-10-16T04:05:02.638+00:00",
      end_time: "2023-10-16T04:05:02.638+00:00",
      duration: 0,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "gh-api.clickhouse.tech (Yandex Demo)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 2 },
        nodes: [],
      },
    },
    {
      id: "fd5964bf-b8a8-4330-8023-4704fdc7a264",
      created_at: "2023-10-16T04:05:02.651383+00:00",
      updated_at: "2023-10-16T04:05:02.651383+00:00",
      request_id: "2c711754-7c67-49f4-8afe-e659922c3c4d-span-1",
      start_time: "2023-10-16T04:05:02.575+00:00",
      end_time: "2023-10-16T04:05:02.579+00:00",
      duration: 4,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "gh-api.clickhouse.tech (Yandex Demo)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 3 },
        nodes: [],
      },
    },
    {
      id: "4aecfde2-dc67-4c60-915e-09fe13ee3868",
      created_at: "2023-10-15T11:27:09.227183+00:00",
      updated_at: "2023-10-15T11:27:09.227183+00:00",
      request_id: "1fb18814-7cf5-45c2-a3fa-a65f40f0fa07-span-1",
      start_time: "2023-10-15T11:26:17.651+00:00",
      end_time: "2023-10-15T11:26:17.653+00:00",
      duration: 2,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "Ecom (demo db)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 3 },
        nodes: [],
      },
    },
    {
      id: "85ea85d7-14f7-4d18-9057-4cd6a5061bab",
      created_at: "2023-10-15T11:27:09.227183+00:00",
      updated_at: "2023-10-15T11:27:09.227183+00:00",
      request_id: "2d69db7e-d078-4abe-aa01-7d96f91e56f9-span-1",
      start_time: "2023-10-15T11:26:19.427+00:00",
      end_time: "2023-10-15T11:26:19.427+00:00",
      duration: 0,
      path: "/cubejs/datasources/v1/meta",
      user: {
        display_name: "demo@mlcraft.io",
        alerts: [],
        alerts_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        datasources: [],
        datasources_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        members: [],
        members_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        reports: [],
        reports_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        versions: [],
        versions_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
      },
      datasource: {
        name: "Ecom (demo db)",
        branches: [],
        branches_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        created_at: undefined,
        dataschemas: [],
        dataschemas_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        db_params: undefined,
        db_type: "",
        explorations: [],
        explorations_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        id: undefined,
        request_logs: [],
        request_logs_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        sql_credentials: [],
        sql_credentials_aggregate: {
          __typename: undefined,
          aggregate: undefined,
          nodes: [],
        },
        updated_at: undefined,
        user: {
          __typename: undefined,
          account: undefined,
          alerts: [],
          alerts_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          avatar_url: undefined,
          branches: [],
          branches_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          created_at: undefined,
          dataschemas: [],
          dataschemas_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          datasources: [],
          datasources_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          display_name: undefined,
          id: undefined,
          members: [],
          members_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          reports: [],
          reports_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          request_logs: [],
          request_logs_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
          updated_at: undefined,
          versions: [],
          versions_aggregate: {
            __typename: undefined,
            aggregate: undefined,
            nodes: [],
          },
        },
        user_id: undefined,
      },
      request_event_logs: [
        { path: "/cubejs/datasources/v1/meta", error: null },
        { path: "/cubejs/datasources/v1/meta", error: null },
      ],
      request_event_logs_aggregate: {
        aggregate: { count: 2 },
        nodes: [],
      },
    },
  ],
};
